# Default values for helm-2to3-migration chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: helm-2to3-migration
namespace: giantswarm

userID: 1000
groupID: 1000

global:
  image:
    registry: quay.io

image:
  registry: quay.io
  name: giantswarm/helm-2to3-migration
  tag: [[ .Version ]]

tiller:
  namespace: "kube-system"
