version: 2.1
orbs:
  architect: giantswarm/architect@2.1.0

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
          wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./architect
          ./architect version
      - run: ./architect build

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-helm-2to3-migration-to-quay
          image: "quay.io/giantswarm/helm-2to3-migration"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-helm-2to3-migration-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/helm-2to3-migration"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: "push-helm-2to3-migration-to-default-catalog"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "helm-2to3-migration"
          requires:
            - push-helm-2to3-migration-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
