apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["/bin/sh" , "-c"]
          args:
            - for r in $(cat /data/config/releases | tr "," "\n"); do 2to3 convert --delete-v2-releases --tiller-ns {{ .Values.tiller.namespace }} "$line"; done;
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}
            namespace: {{ .Values.Namespace }}
      restartPolicy: Never
  backoffLimit: 3
