apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  releases: |-
    {{ join "," .Values.releases }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-scripts
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  run.sh: |-
    #!/bin/sh

    i=0
    j=0

    for r in $(cat /data/config/releases | tr "," "\n");
    do
      errFile=$(mktemp)
      2to3 convert --tiller-ns {{ .Values.tiller.namespace }} "$r" 2>$errFile
      ret=$?

      cat $errFile

      if [[ $ret -gt 0 ]]; then
        if [[ $(cat errFile) ==  *"has no deployed releases"* ]]; then
           i=$((i+1));
        else
           j=$((j+1));
        fi
      else
         kubectl -n {{ .Values.tiller.namespace }} get cm -lNAME=$r -o yaml | sed 's/\(OWNER: TILLER\)/OWNER: HELM-BACKUP-V2/' | kubectl replace -f -
      fi
    done;

    if [ $i -gt 0 ]; then
      echo "Already migrated $i releases";
    fi

    if [ $j -gt 0 ]; then
      echo "Failed $j times";
      exit 127;
    fi

