apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["/scripts/run.sh"]
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
            - name: scripts
              mountPath: /scripts/run.sh
              subPath: run.sh
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}
            namespace: {{ .Values.Namespace }}
        - name: scripts
          configMap:
            defaultMode: 511
            name: {{ .Values.name }}-scripts
            namespace: {{ .Values.Namespace }}
      restartPolicy: OnFailure
  backoffLimit: 3
