kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  podSelector:
    matchLabels:
      job-name: {{ .Values.name }}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
