apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - "create"
      - "delete"
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ .Values.name }}
    verbs:
      - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
